### ISSUE TITLE
Request for adding a rolling tag v1 for GitHub Actions

### ISSUE THREAD

**Issue by kt81** [cjlapao/simple-badge-generator-action#21]
**Is your feature request related to a problem? Please describe.**
It is a common practice for GitHub Actions to have a rolling tag for major versions, such as v1, in addition to specific patch versions like v1.0.0. Currently, the lack of a rolling tag for the major version forces users to specify minor versions (e.g., v1.0), which is inconvenient and can lead to unnecessary specificity in version management.

**Describe the solution you'd like**
Creation of a rolling tag v1 (a tag that is updated to always refer to the latest release within a major version).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Thank you!

**Comment by cjlapao** [comment]
@kt81 this has been done now, I have added a new version and this is now tagged also with the v1 and latest to help.

Let me know if you need anything else

**Comment by kt81** [comment]
Thank you so much!

I've been using this great action and have noticed a few areas for minor improvements, particularly in the documentation. I'm planning to suggest these small changes through a PR soon.

Thanks again for your quick response and support!

**Comment by cjlapao** [comment]
@kt81 Amazing, good to know it helps. and yes, please raise a pr and I will review it, any help or suggestion is welcome
